//Scripts.dump();
//Scripts.execStorage("test.tjs");

var isFaild = true;
function simpleCall() { isFaild = false; }
simpleCall();
if( isFaild ) {
	throw new Exception("faild: function simpleCall()");
}

function argMul( a, b ) { return a * b; }
if( argMul(2,3) != 6 ) {
	throw new Exception("faild: function argMul( a, b )");
	isFaild = true;
}
function blankCall( a, b ) {
	if( a === void && b == 5 ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !blankCall(,5);
if( isFaild ) {
	throw new Exception("faild: function blankCall(a,b)");
}
function afterBlankCall( a, b ) {
	if( a == 5 && b === void ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !afterBlankCall(5);
if( isFaild ) {
	throw new Exception("faild: function afterBlankCall(a,b)");
}

function defaultArg( a = 1, b = 2 ) {
	if( a == 1 && b == 2 ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !defaultArg();
if( isFaild ) {
	throw new Exception("faild: function defaultArg(a,b)");
}
function defaultArg2( a = 1, b = 2 ) {
	if( a == 5 && b == 2 ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !defaultArg2(5);
if( isFaild ) {
	throw new Exception("faild: function defaultArg2(a,b)");
}
function argressFunc {
	return true;
}
isFaild = !argressFunc();
if( isFaild ) {
	throw new Exception("faild: function argressFunc()");
}

var funcVar = function(i) { return i*5; };
if( funcVar(5) != 25 ) {
	throw new Exception("faild: function funcVar");
}
function argThrough() {
	return argMul(...);
}
if( argThrough(5,3) != 15 ) {
	throw new Exception("faild: function argThrough()");
	isFaild = true;
}
function arrayArg( a* ) {
	if( a[0] == 1 && a[1] == 2 && a[2] == 3 && a[3] == 4 ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !arrayArg(1,2,3,4);
if( isFaild ) {
	throw new Exception("faild: function arrayArg()");
}
function arrayArg2( x, a* ) {
	if( x == 0, a[0] == 1 && a[1] == 2 && a[2] == 3 && a[3] == 4 ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !arrayArg2(0,1,2,3,4);
if( isFaild ) {
	throw new Exception("faild: function arrayArg2()");
}
function arrayArg3( x, a* ) {
	if( x == 0 && a[0] == 1 && a[1] == 2 && a[2] == 3 && a[3] == 4 ) {
		return true;
	} else {
		return false;
	}
}
isFaild = !arrayArg3(0,1,2,3,4);
if( isFaild ) {
	throw new Exception("faild: function arrayArg3()");
}

var argsArray = [1, 2, 3, 4];
isFaild = !arrayArg(argsArray*);
if( isFaild ) {
	throw new Exception("faild: function arrayArg(argsArray*)");
}
argsArray = [ 2, 3 ];
isFaild = !arrayArg(1,argsArray*,4);
if( isFaild ) {
	throw new Exception("faild: function arrayArg(1,argsArray*,4)");
}

function argThrough2(*) {
	return argMul(*);
}
if( argThrough2(4,3) != 12 ) {
	throw new Exception("faild: function argThrough2(*)");
	isFaild = true;
}
function argThrough3(ar*) {
	return argMul(ar*);
}
if( argThrough3(4,6) != 24 ) {
	throw new Exception("faild: function argThrough3(*)");
	isFaild = true;
}

function argThrough4(a,*) {
	return argMul(a,*);
}
if( argThrough4(4,5) != 20 ) {
	throw new Exception("faild: function argThrough4(*)");
	isFaild = true;
}